spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /api
data:
  organisms:
    walk:
    - dog
    - cat
    - mouse
    swim:
    - fish
    - eel
    fly:
    - bird
    - penguin
